staff-mode:
  default-gamemode: 'survival'
  inventory:
    - item:
        slot: 0
        item:
          name: 'test'
          description:
            - 'test'
          item: 'diamond_sword'
          amount: 1