name: StaffManagerCore
version: '1.0.0'
main: io.github.cassiboy1203.staffmanagercore.StaffManagerCore
api-version: '1.21'
authors:
  - cassiboy1203
commands:
  staff:
    description: Enters staff mode
    permission: staffmanager.staff
  gamemode:
    description: Allows you to change your gamemode
    permission: staffmanager.staff.gamemode
    aliases:
      - 'gm'
      - 'gmc'
      - 'gms'
      - 'gmsp'
      - 'gma'

permissions:
  staffmanager.staff:
    description: Allows the player to enter staff mode with /staff
  staffmanager.staff.vanish:
    description: Makes the player invisible in staff mode to players without de see invisible permission
  staffmanager.staff.fly:
    description: Allows the player to fly in staff mode
  staffmanager.staff.god:
    description: Give the player godmode in staff mode
  staffmanager.staff.see.invisible:
    description: Allows the player to see invisible players in staff mode
    default: not op
  staffmanager.see.invisible:
    description: Allows the player to see invisible players outside of staff mode
    default: not op
    children:
      staffmanager.staff.see.invisible: true
  staffmanager.staff.gamemode:
    description: Allows the player to change gamemode while in staff mode
  staffmanager.gamemode:
    description: Allows the player to change gamemode even while outside staff mode
    children:
      staffmanager.staff.gamemode: true
  staffmanager.staff.gamemode.other:
    description: Allows the player to change another players gamemode while in staff mode
  staffmanager.gamemode.other:
    description: Allows the player to change another players gamemode even while outside staff mode
    children:
      staffmanager.staff.gamemode.other: true